import functools
from collections.abc import Sequence

from bst_node import BstNode
from test_framework import generic_test
from test_framework.binary_tree_utils import (binary_tree_height,
                                              generate_inorder)
from test_framework.test_failure import TestFailure
from test_framework.test_utils import enable_executor_hook


def build_min_height_bst_from_sorted_array(
        nums: Sequence[int]) -> BstNode | None:
    """
    #14.8

    Time complexity = O(n)
    Space complexity = O(log n) on function call stack.

    The time complexity T(n) satisfies the recurrence T(n) = 2T(n/2) + O(1),
    which solves to T(n) = O(n). Another explanation for the time complexity
    is that we make exactly n calls to the recursive function and spend O(1)
    within each call.

    Test PASSED (87/87) [   3 us]
    Average running time:   12 us
    Median running time:     6 us
    """

    def build_min_height_bst_from_sorted_subarray(start: int, end: int):
        if end <= start:
            return None

        mid = start + ((end - start) >> 1)
        return BstNode(
            nums[mid],
            build_min_height_bst_from_sorted_subarray(start, mid),
            build_min_height_bst_from_sorted_subarray(mid + 1, end)
        )

    return build_min_height_bst_from_sorted_subarray(0, len(nums))


def build_min_height_bst_iterative(nums: list[int]) -> BstNode | None:
    """
    An iterative version generated by Gemini :)

    Time complexity = O(n)
    Space complexity = O(log n) on function call stack.

    Test PASSED (87/87) [   4 us]
    Average running time:   15 us
    Median running time:     8 us
    """
    if not nums:
        return None

    # 1. Create the root node first to give the stack a starting point
    mid = len(nums) >> 1
    root = BstNode(nums[mid])

    # 2. Stack stores tuples of:
    # (parent_node, start_index, end_index, is_left_child)
    stack = [
        (root, 0, mid, True),  # Represents the left subtree
        (root, mid + 1, len(nums), False)  # Represents the right subtree
    ]

    # 3. Process the explicit stack
    while stack:
        parent, start, end, is_left = stack.pop()

        if start >= end:
            continue

        # Calculate mid and create the new node
        curr_mid = start + ((end - start) >> 1)
        node = BstNode(nums[curr_mid])

        # Link the newly created node to its parent
        if is_left:
            parent.left = node
        else:
            parent.right = node

        # Push the next boundaries onto the stack
        # (Pushing right then left means left gets popped and processed first,
        # though order doesn't strictly matter for correctness here)
        if curr_mid + 1 < end:
            stack.append((node, curr_mid + 1, end, False))
        if start < curr_mid:
            stack.append((node, start, curr_mid, True))

    return root


@enable_executor_hook
def build_min_height_bst_from_sorted_array_wrapper(executor, arg):
    result = executor.run(
        functools.partial(build_min_height_bst_from_sorted_array, arg))

    if generate_inorder(result) != arg:
        raise TestFailure('Result binary tree mismatches input array')
    return binary_tree_height(result)


if __name__ == '__main__':
    exit(
        generic_test.generic_test_main(
            'bst_from_sorted_array.py',
            'bst_from_sorted_array.tsv',
            build_min_height_bst_from_sorted_array_wrapper))
